In [2]:
import numpy
import torch

#import packages
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torch.utils.data import SubsetRandomSampler

#declare LRDataset class
class LRDataset(Dataset):
  def __init__(self,data_points):
    self.data_points = data_points
    
  def __getitem__(self,index):
    x = torch.tensor(self.data_points[index][0],dtype=torch.float)
    y = torch.tensor(self.data_points[index][1],dtype=torch.float)
    return x,y

  def __len__(self):
        return len(self.data_points)

#declare LRDataset class
class LRModel(torch.nn.Module):
  def __init__(self):
    super(LRModel,self).__init__()
    self.a = torch.nn.Parameter(torch.rand(1),requires_grad=True)
    self.b = torch.nn.Parameter(torch.rand(1),requires_grad=True)

  def forward(self,x):
    return self.a*x + self.b

data_points = numpy.array([[0.11, 1.24],  
              [0.20, 1.40], 
              [0.49, 2.00],
              [0.65, 2.27],
              [0.67, 2.41],
              [0.83, 2.52]])

#set hyper-parameters
n_epoch = 4000
batch_size = 2
eta = 0.01

#define object for data providing
lr_dataset = LRDataset(data_points)
index = list(range(len(lr_dataset)))
sampler = SubsetRandomSampler(index)
lr_loader = DataLoader(dataset=lr_dataset,\
            batch_size=batch_size,\
            sampler=sampler)

#define model and optimizer
lr_model = LRModel()

optimizer = torch.optim.SGD(lr_model.parameters(),eta)

#run learning paradigm
for epoch in range(n_epoch):
  for x,y in lr_loader:
    lr_model.train()
    y_hat = lr_model(x)
    
    y_error = y - y_hat
    mse_loss = (y_error **2).mean()
                    
    mse_loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()
        
  print(f'\n{epoch}:{lr_model.a}:{lr_model.b}')

串流輸出內容已截斷至最後 5000 行。

2750:Parameter containing:
tensor([1.8823], requires_grad=True):Parameter containing:
tensor([1.0481], requires_grad=True)

2751:Parameter containing:
tensor([1.8822], requires_grad=True):Parameter containing:
tensor([1.0480], requires_grad=True)

2752:Parameter containing:
tensor([1.8823], requires_grad=True):Parameter containing:
tensor([1.0480], requires_grad=True)

2753:Parameter containing:
tensor([1.8823], requires_grad=True):Parameter containing:
tensor([1.0481], requires_grad=True)

2754:Parameter containing:
tensor([1.8823], requires_grad=True):Parameter containing:
tensor([1.0481], requires_grad=True)

2755:Parameter containing:
tensor([1.8823], requires_grad=True):Parameter containing:
tensor([1.0480], requires_grad=True)

2756:Parameter containing:
tensor([1.8823], requires_grad=True):Parameter containing:
tensor([1.0480], requires_grad=True)

2757:Parameter containing:
tensor([1.8823], requires_grad=True):Parameter containing:
tensor([1.0480], require